version: '3.9'
services:
  db:
    container_name: postgres
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      PGDATA: /data/postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/data/postgres
    networks:
      - db

networks:
  db:
    driver: bridge

volumes:
  db:
